-- DEPRECATED: This migration is replaced by 023_create_time_entries_table.sql and 024_create_break_periods_table.sql
-- The admin timecard adjustment columns are now created as part of migration 023
-- This file is kept for git history but no longer needs to be applied
